services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
        VITE_SOCKET_URL: ""
        VITE_GOOGLE_CLIENT_ID: "379222873072-qek39tmb4aa91t2dl0tutb3rpfducjka.apps.googleusercontent.com"
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
